# Generated by Django 4.1.7 on 2023-03-06 19:04

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_photo',
            field=models.ImageField(blank=True, storage=blog.models.UserPhotoStorage(), upload_to='user_photo/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, storage=blog.models.PostImagesStorage(), upload_to='post_images'),
        ),
    ]
