# Generated by Django 4.1.7 on 2023-03-06 19:28

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_author_profile_photo_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, storage=blog.models.PostImagesStorage(), upload_to='post_images/'),
        ),
    ]
